auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: birdinforest
url: http://birdinforest.com
feed: /atom.xml
author_info: <a href="http://birdinforest.com/">DerekW</a>
